{% set name = "nameparser" %}
{% set version = "0.5.6" %}
{% set sha256 = "de2dac86c60f3da6c86d28109a51be8bf54a7148a837c5ead6cec41547813a45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/derek73/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nameparser

about:
  home: http://github.com/derek73/python-nameparser
  license: LGPL-2.1+
  license_family: LGPL
  license_file: LICENSE
  summary: 'A simple Python (3.2+ & 2.6+) module for parsing human names into their individual components.'

extra:
  recipe-maintainers:
    - CJ-Wright
