{% set name = "nameparser" %}
{% set version = "1.1.1" %}
{% set sha256 = "8893f3134383eec6201c02e2426b4f9897b21ba2b6aedce6b55b46d1fde907e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/derek73/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nameparser

about:
  home: http://github.com/derek73/python-nameparser
  license: LGPL-2.1+
  license_family: LGPL
  license_file: LICENSE
  summary: A simple Python (3.2+ & 2.6+) module for parsing human names into their individual components.

extra:
  recipe-maintainers:
    - CJ-Wright
